* TODOx Case 0001: asaMpAwya [[http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=ccs&page=036-1][page 036-1]] 
ccs:asaMpAwya,2326:asaMpAWya:t:
;   .{#asaMpAwya#}¦ nicht zum Studiengenossen zu |machen. 
* TODOx Case 0002: Aryavfkta [[http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=ccs&page=044-1][page 044-1]] 
ccs:Aryavfkta,2839:Aryavftta:t:
;   .{#Aryavfkta#}^1¦ von ehrenhaftem Betragen. 
* TODOx Case 0003: tasTuzas [[http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=ccs&page=150-1][page 150-1]] 
ccs:tasTuzas,8391:tasTuzas:n:
;   .{#tasTuzas#}¦ {#tasTus#} {%s.%} 1. {#sTA.#} 
* TODOx Case 0004: DarmADikAranika [[http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=ccs&page=193-1][page 193-1]] 
ccs:DarmADikAranika,10984:DarmADikAraRika:t:
;   .{#DarmADikAranika#}¦ {#°kArin#} {%u.%} {#°kfta#} {%m.%} Richter. 
* TODOx Case 0005: Dftasnu [[http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=ccs&page=117-1][page 117-1]] 
ccs:Dftasnu,6652:Gftasnu:t:
;   .{#Dftasnu/#}^1¦ = {%vor.%} 
* TODOx Case 0006: nyasIkar [[http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=ccs&page=228-1][page 228-1]] 
ccs:nyasIkar,12938:nyAsIkar:t: = cae nyAsIkf
;   .{#nyasIkar#}¦   jemd. etwas anvertrauen. 
* TODOx Case 0007: pfzWamAMa [[http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=ccs&page=263-1][page 263-1]] 
ccs:pfzWamAMa,14952:pfzWamA/Ma:pfzWamA/Msa:t:
;   .{#pfzWamA/Ma#}¦ {%n.%} das Rückenfleisch; {#°saM KAd#} das |R. jemds.
;  essen {%d. i.%} afterreden. 
* TODOx Case 0008: praCi [[http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=ccs&page=267-1][page 267-1]] 
ccs:praCi,15192:praCi:n: verb with anubanDa ?
;   .{#praCi#}¦ = {#praC#} {%(g.).%} 
* TODOx Case 0009: maRImaya [[http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=ccs&page=315-1][page 315-1]] 
ccs:maRImaya,17845:maRimaya:t:
;   .{#maRImaya,#}¦ {%f.%} {#I#} aus Juwelen {%o.%} Kristallen |gebildet. 
